### ISSUE TITLE
Espionage: Bug Tracker

### ISSUE THREAD

**Issue by darkshade9** [actionquake/aq2-tng#142]
Espionage General Bugs

- [x] Cop and Robber icons showing up instead of ctf_r/ctf_b icons on team score HUD.  Likely due to reading the values from `action.ini` instead of taking in the values from the `.esp` file or safe defaults.  Look at lines 725-727 in `esp.c` or in the `SP_worldspawn` function lines ~1695
- [x] Players are not spawning together as a team
  - [x] Fixed by using teamplay-logic function on initial spawn, and when the round is ongoing, use the espionage respawn logic 
- [x] Hitting PF_SoundIndex fatal errors now, do we have too many sounds loaded?
  - [x] Too many sounds loaded, pared back the sndlist.ini, also precaching insane sounds now

**Comment by darkshade9** [comment]
Assassinate the Leader (ATL) Bugs

- [x] If it's 1v1, both players leader up and round begins, one player switches teams, they will switch but the round does not end even though there are no more people on the other team
  - [x] Prevent team change as leader
- [x] Disconnecting mid-round as leader does not establish a new leader
  - [x] Call EspLeaderCheck() on ClientDisconnect and ensure it chooses a new leader immediately
- [x] Volunteering for leader when a team already has a leader should set that players' `is_volunteer` state to true and messaging stating such
- [ ] Player can un-leader in mid round but that should not remove their leadership role for that round, only that it will not persist to the next round.  This sets their `is_volunteer` state to `false` and will only be re-elected leader next round if no one else has volunteered and are randomly selected to do so
  - [x] Set it so that players cannot un-leader in mid-round, but if they disconnect, it will initiate a search process to immediately find a volunteer or a bot

**Comment by darkshade9** [comment]
Escort the VIP (ETV) Bugs

- [x] PF_SoundIndex tng/flagcap.wav overflow error on capturing the flag
  - [x] This is due to too many sounds in the game, need to pare back the count

**Note:  With additions to the `aqtion-alpha` branch from skuller's q2pro master branch, we now have 2047 sounds rather than 255, so this should not be a problem once this version is live.**
