### ISSUE TITLE
Espionage: Test Tracker

### ISSUE THREAD

**Issue by darkshade9** [actionquake/aq2-tng#143]
All modes:
- [x] All teams skins are set correctly (crew and leader)
- [x] Round ends immediately when a leader is killed
- [x] Team point awarded correctly
- [x] `esp_punish` works as expected
  - [x] `esp_punish 0` is exactly like normal teamplay, after-round FF is on
  - [x] `esp_punish 1` kills all of the players of the losing team immediately
  - [x] `esp_punish 2` gives the winning team an invulnerability shield for the remainder of the post-round
- [ ] Players spawn at the correct spawnpoints
  - [x] All players of each team spawn together on round start, rather than distributed around the map, just like regular teamplay
  - [ ] Custom spawnpoints (from the .esp file)
  - [ ] Default spawnpoints from the map bsp data
  - [x] Respawns occur on the leader (ATL, ETV Team 1), or at the original spawnpoint (ETV Team 2)
  - [x] Respawns halt immediately at the end of the round
- [ ] Custom awards are given correctly -- These all have cooldowns associated
  - [ ] Killing enemy team leader: 5 points
  - [ ] Defending your own leader: 2 points
  - [ ] Harassing (not killing) enemy team leader: 1 point
  - [ ] Capturing the briefcase as leader: 5 points
  - [ ] Defending the briefcase: 2 points
- [x] All teams have a visible scoreboard like in CTF mode with the proper pic icons associated
- [ ] Leader leaving mid-round elects a new leader at random on that team in non-matchmode
  - [ ] In matchmode, this awards the other team the win and pauses the game until a new captain is chosen
- [ ] Both modes work in Matchmode
---
ATL:
- [x] All teams spawn with a leader
- [ ] All of this works with 3Team as well
---
ETV:
- [x] Only TEAM1 spawns with a leader
- [ ] 3Team forcibly disabled
- [x] Flag spawns at the correct location
- [x] Flag is only captureable by the leader of TEAM1
- [x] Round ends immediately when flag is captured
- [ ] Points awarded appropriately when flag is captured
- [x] Flag resets every round correctly so it can be recaptured
- [x] Cannot re-capture flag more than once in the same round
- [ ] Halftime does not auto-start without a leader on Team 1

**Comment by darkshade9** [comment]
Things we cannot resolve to my knowledge:
- [ ] Validating that custom spawn points are good spawn points -- bad ones can spawn players anywhere, even outside of the map.  This comes down to bad config.
- [ ] We can't use Leader pics anywhere because we've run out of `ps.stats` unless the GHUD lets us get around that limitation
  - [x] Update here, we can use Leader pics in the GHUD
